services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lamp_web
    volumes:
      - ./www:/var/www/html
    ports:
      - "80:80"
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: lamp_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "13306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db_scripts:/docker-entrypoint-initdb.d
      - ./mysql-conf/my.cnf:/etc/mysql/conf.d/my.cnf
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:5-apache
    platform: linux/amd64
    container_name: lamp_phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
      PMA_USER: ${MYSQL_ROOT_USER}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"

  nodejs:
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    container_name: nodejs_app
    ports:
      - "3000:3000"
    volumes:
      - ./nodejs:/usr/src/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  db_data:
  mongo_data:
